accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views
from .forms import CustomLoginForm


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form=CustomLoginForm),  name='login'),
]

api/urls.py
from django.urls import path, include

from api.views import PostViewSet, UserViewSet

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls))
]

blogapp/urls.py
from .views import blog_views, dashboard_views
from django.urls import path

urlpatterns = [
    path('posts/', dashboard_views.PostList.as_view(), name='posts'),
    path('add/', dashboard_views.PostCreate.as_view(), name='new_post'),
    path('edit/<slug:slug>/', dashboard_views.PostUpdate.as_view(), name='edit_post'),


    path('', blog_views.PostList.as_view(), name='home'),
    path('<slug:slug>/', blog_views.PostDetail.as_view(), name='post_detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic.base import TemplateView
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blogapp.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='blog_home'),

]

accounts/models.py
from django.db import models

# Create your models here.

api/models.py
from django.db import models

# Create your models here.

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.forms.widgets import PasswordInput, TextInput


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'validate', 'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Password'}))


class CustomSignUpForm(UserCreationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'validate', 'placeholder': 'Username'}))
    password1 = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    def __init__(self, *args, **kwargs):
        super(CustomSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

blogapp/forms.py
from django import forms
from blogapp.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'status']

accounts/views.py
# from django.shortcuts import render

# Create your views here.
from django.contrib.auth import authenticate, login
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect

from .forms import CustomSignUpForm


class SignUp(generic.CreateView):
    form_class = CustomSignUpForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        # save new user
        form.save()

        # get username and password
        username = self.request.POST['username']
        password = self.request.POST['password1']

        # authenticate user
        user = authenticate(username=username, password=password)
        user.save()

        # assign privileges
        group = Group.objects.get(name='Author')
        user.groups.add(group)

        # log user in
        login(self.request, user)
        # this is the correct version but it is not working
        # return HttpResponseRedirect(self.get_success_url)
        return HttpResponseRedirect(reverse_lazy('home'))

api/views.py
from django.contrib.auth.models import User
from blogapp.models import Post

from api.serializers import UserSerializer, PostSerializer

from rest_framework import viewsets, permissions
from api.permissions import IsAuthorOrReadOnly

from django.template.defaultfilters import slugify


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,
                          IsAuthorOrReadOnly]

    def perform_create(self, serializer):
        author = self.request.user
        title = self.request.data['title']
        
        slug = slugify("{title} by {author}".format(title=title, author=author.username))

        serializer.save(author=author, slug=slug)

blogapp/views/blog_views.py
# from django.shortcuts import render
from django.views import generic
from ..models import Post


# Create your views here.
class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

blogapp/views/dashboard_views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django_tables2 import RequestConfig
from blogapp.tables import PostTable
from blogapp.models import Post
from blogapp.forms import PostForm

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from guardian.mixins import PermissionRequiredMixin

from django.shortcuts import get_object_or_404


# Create your views here.
class PostList(LoginRequiredMixin, generic.ListView):
    template_name = 'dashboard/posts.html'
    paginate_by = 20
    ordering = ['-created_on']

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        table = PostTable(self.get_queryset())
        RequestConfig(self.request).configure(table)
        context['table'] = table
        return context


class PostUpdate(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    form_class = PostForm
    template_name = 'dashboard/edit_post.html'
    success_url = reverse_lazy('posts')
    permission_required = 'change_post'

    def get_object(self):
        """Returns the Post instance that the view displays"""
        return get_object_or_404(Post, slug=self.kwargs.get("slug"))


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    # fields = ['title', 'slug', 'author', 'content', 'status']
    template_name = 'dashboard/new_post.html'
    success_url = reverse_lazy('posts')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreate, self).form_valid(form)

templates/base/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Kingdom Coding</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Kingdom Coding Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        {% block navbar %}
                          <!-- Login Goes here -->
                        {% endblock navbar %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Kingdom Coding</p>
        </footer>
    </body>
</html>

templates/base/form_base.html
{% extends "base/base.html" %}

{% block content %}
  {% include "includes/style_tag.html" %}
  {% include "includes/header.html" %}

  <div class="container">
      <div class="row">
          <!-- Blog Entries Column -->
          <div class="col-md-6 offset-md-3 mt-3">
              <div class="card mb-4">
                  <div class="card-body d-flex justify-content-center">
                    {% block form %}
                      <!-- Form Entries Go Here -->
                    {% endblock form %}
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

templates/base/post_base.html
{% extends 'base/base.html' %}

{% block navbar %}
    <a href="{% url 'posts' %}" class="navbar-brand text-black font-weight-bold">Hi {{ user.username }}!</a>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
    </li>
{% endblock navbar %}

{% block content %}
    {% include "includes/style_tag.html" %}
    <div class="container">
      <div class="row">
        <div class="col-md-12 card mb-4  mt-3 left  top">
          <div class="card-body d-flex justify-content-center">
            <form class="" action="" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="col text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

templates/dashboard/edit_post.html
{% extends 'base/post_base.html' %}

templates/dashboard/new_post.html
{% extends 'base/post_base.html' %}

templates/dashboard/posts.html
{% extends "base/base.html" %}
{% load querystring from django_tables2 %}
{% load trans blocktrans from i18n %}

{% block navbar %}
    <a href="{% url 'posts' %}" class="navbar-brand text-black font-weight-bold">Hi {{ user.username }}!</a>

    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'new_post' %}">Add Post</a>
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
    </li>
{% endblock navbar %}

{% block content %}
  {% include "includes/style_tag.html" %}
  {% include "includes/header.html" %}

  <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
          {% block table.thead %}
          <thead>
            <tr>
              {% for column in table.columns %}
                  {% if column.orderable %}
                  <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header|title }}</a></th>
                  {% else %}
                  <th {{ column.attrs.th.as_html }}>{{ column.header|title }}</th>
                  {% endif %}
              {% endfor %}
            </tr>
          </thead>
          {% endblock table.thead %}


            {% block table.tbody %}
            <tbody>
                {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                  {% block table.tbody.row %}
                  <tr class='{% cycle "odd" "even" %}'>
                  <!--<tr class="{% cycle "odd" "even" %}">-->
                      {% for column, cell in row.items %}
                          <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                      {% endfor %}
                  </tr>
                  {% endblock table.tbody.row %}
                {% empty %}
                  {% if table.empty_text %}
                  {% block table.tbody.empty_text %}
                  <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                  {% endblock table.tbody.empty_text %}
                  {% endif %}
                {% endfor %}
            </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot></tfoot>
            {% endblock table.tfoot %}
        </table>
    </div>


{% endblock content%}

templates/includes/header.html
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to our awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

templates/includes/sidebar.html
<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django' and the template was adapted from DjangoCentral.</p>
        <p class="card-text">You can checkout DjangoCentral and if you are interested in Django, the official documentation is a great place to learn</p>
        <div class="card-body d-flex justify-content-around">
          <a href="https://djangocentral.com/"
             class="btn btn-danger">DjangoCentral!</a>
           <a href="https://docs.djangoproject.com/en/2.2/"
              class="btn btn-danger">Learn Django!</a>
      </div>
    </div>
</div>
</div>

templates/includes/style_tag.html
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

templates/index.html
{% extends "base/base.html" %}

{% block navbar %}
  {% if user.is_authenticated %}
    <li class="navbar-brand text-black font-weight-bold">
      Hi {{ user.username }}!
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'new_post' %}">Add Post</a>
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'posts' %}">Edit Post</a>
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
  <li class="nav-item text-black">
      <a class="nav-link text-black font-weight-bold" href="{% url 'signup' %}">Sign Up</a>
  </li>
  <li class="nav-item text-black">
      <a class="nav-link text-black font-weight-bold" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
{% endblock navbar %}

{% block content %}
  {% include "includes/style_tag.html" %}
  {% include "includes/header.html" %}

  <div class="container">
      <div class="row">
          <!-- Blog Entries Column -->
          <div class="col-md-8 mt-3 left">
              {% for post in post_list %}
              <div class="card mb-4">
                  <div class="card-body">
                      <h2 class="card-title">{{ post.title }}</h2>
                      <p class="card-text text-muted h6">{{ post.Author }} | {{ post.created_on}} </p>
                      <p class="card-text">{{post.content|slice:":200" }}</p>
                      <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                  </div>
              </div>
              {% endfor %}
          </div>
          {% block sidebar %} {% include 'includes/sidebar.html' %} {% endblock sidebar %}
      </div>
  </div>
{% endblock %}

templates/post_detail.html
{% extends 'base/base.html' %}

{% block navbar %}
  {% if user.is_authenticated %}
    <li class="navbar-brand text-black font-weight-bold">
      Hi {{ user.username }}!
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'new_post' %}">Add Post</a>
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'posts' %}">Edit Post</a>
    </li>
    <li class="nav-item text-black">
        <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
    </li>
  {% else %}
  <li class="nav-item text-black">
      <a class="nav-link text-black font-weight-bold" href="{% url 'signup' %}">Sign Up</a>
  </li>
  <li class="nav-item text-black">
      <a class="nav-link text-black font-weight-bold" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
{% endblock navbar %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'includes/sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}